baseURL = "https://hackjumpzero.ca/"
languageCode = "en-us"
title = "HJZ's Space"
theme = "hello-friend-ng"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts"

[[menu.main]]
  identifier = "notes"
  name       = "Notes"
  url        = "https://notes.hackjumpzero.ca/"
